module.exports.recipes = [
  {
    img: 'https://cdn.pixabay.com/photo/2017/02/07/23/12/chocolate-2047248_960_720.jpg',
    title: 'Dairy Free Chocolate Pudding (Serving Size: 2)',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
  {
    img: 'https://static.pexels.com/photos/262325/pexels-photo-262325.jpeg',
    title: 'Tasty burger',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
  {
    img: 'https://static.pexels.com/photos/414578/pexels-photo-414578.jpeg',
    title: 'Camera',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
  {
    img: 'https://static.pexels.com/photos/66627/pexels-photo-66627.jpeg',
    title: 'Morning',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
  {
    img: 'https://static.pexels.com/photos/139446/pexels-photo-139446.jpeg',
    title: 'Hats',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
  {
    img: 'https://static.pexels.com/photos/158607/cairn-fog-mystical-background-158607.jpeg',
    title: 'Honey',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
  {
    img: 'https://static.pexels.com/photos/20974/pexels-photo.jpg',
    title: 'Vegetables',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
  {
    img: 'https://static.pexels.com/photos/39811/pexels-photo-39811.jpeg',
    title: 'Water plant',
    restrictions: 'dairy-free, no sugar',
    benefits: 'Chocolate is the best dietary source of magnesium, a mineral that is important for helping to metabolize estrogen and balancing our hormones. This recipe is a fabulous go to during the second half of the cycle – the luteal phase, particularly if you are stressed or experiencing PMS symptoms such as bloating, poor sleep, anxiety and cramping.',
    ingredients: [
      '3 ripe avocados',
      '5 dates (soak for 3 hours before)',
      '2 tbsp. maple syrup (adjust according to desired sweetness)',
      '½ cup raw cacao powder',
      '½ cup hemp or coconut milk',
      '1 tsp. cinnamon',
      '1 tsp. vanilla extract',
      '½ tsp. pink Himalayan salt',
      '2 tsps. blueberries',
      '1 piece dark unsweetened chocolate (broken into tiny pieces)',
      '2 mint leaves',
    ],
    directions: [
      'Add all ingredients besides the chocolate, blueberries, and mint to a food processor and blend until smooth.',
      'Decorate with chocolate pieces, blueberries and mint leaves to serve.',
    ],
  },
]
